title: Course materials for FANR 6750
name: Richard Chandler
description: Course materials
# theme: jekyll-theme-minimal
# remote_theme: chesterhow/tale
theme: minima
header_pages:
  - README.md
  - syllabus.md
