title: Course materials for FANR 6750
name: Richard Chandler
description: A course on experimental design and analysis
# theme: jekyll-theme-minimal
# remote_theme: chesterhow/tale
theme: minima
header_pages:
  - syllabus.md
  - labs/labs.md